spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop

server:
  port: 8080

datasource:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: toor
  driver-class-name: org.postgresql.Driver

authentication:
  delay: 60